config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'general#dashboard'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :sign_out, to: 'sessions#destroy'

    resources :books
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  has_secure_password

  validates :name, presence: true,
                   length: { in: 3..25 },
                   format: { with: /\A[a-z0-9][a-z0-9_\-]*\z/i }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

class Admin::ApplicationController < ApplicationController
  before_action :require_admin

  private

  def current_admin
    @admin ||= Admin.find_by(id: session[:admin_id])
  end

  def require_admin
    redirect_to admin_login_path unless current_admin
  end
end

app/controllers/admin/general_controller.rb
# frozen_string_literal: true

class Admin::GeneralController < Admin::ApplicationController
  def dashboard; end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Admin::ApplicationController
  skip_before_action :require_admin

  def new
    redirect_to admin_root_path if current_admin
  end

  def create
    if admin = Admin.find_by(name: params[:name]).try(:authenticate, params[:password])
      session[:admin_id] = admin.id
      redirect_to admin_root_path, notice: 'Đăng nhập thành công!'
    else
      flash.now[:alert] = 'Đăng nhập thất bại!'
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to admin_login_path, notice: 'Bạn đã thoát.'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/general/dashboard.html.erb
<header>
  <h1 class="is-size-2"> Dashboard </h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Purange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/admin_navbar' unless controller_name == 'sessions' %>
    <%= render 'shared/admin_header' unless controller_name == 'sessions' %>
    <div class="parent">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_admin_header.html.erb
<% if message = notice || alert %>
  <article class="message <%= notice ? 'is-success' : 'is-danger' %>">
    <div class="message-body">
      <%= message %>
    </div>
  </article>
<% end %>

app/views/shared/_admin_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/admin">
      <%= image_tag 'logo.png', size: '112x27' %>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Sách
        </a>

        <div class="navbar-dropdown">
          <%= link_to 'Tạo mới', new_admin_book_path, class: 'navbar-item' %>
          <%= link_to 'Danh sách', admin_books_path, class: 'navbar-item' %>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to 'Thoát', admin_sign_out_path, method: :delete, class: 'button is-light' %>
        </div>
      </div>
    </div>
  </div>
</nav>